module.exports = [
  'PENDING', 
  'REQUESTED', 
  '2FA_VALIDATED', 
  'EXPIRED', 
  '2FA_VALIDATED_PAYMENT_PENDING', 
  'PAYMENT_PROCESSED', 
  'PAYMENT_STATUS_PENDING', 
  'SYSTEM_UPDATE_AWAITING',
  'SEND_TO_RTA',
  'INVALID_TRANSACTION',
  'RTA_PROCESSED',
  'RTA_REJECTED',
  'ALLOTTED',
  'ALLOTMENT_PENDING'
]