
const transactionFields = {
  switchMfAmcName: "Switch MF AMC Name",
  switchFromScheme: "Switch From Scheme",
  switchToScheme: "Switch To Scheme",
  switchSchemeOption: "Switch Scheme Option",
  switchFolio: "Switch Folio",
  switchTransactionUnits_Amount: "Switch Transaction Units/Amount",
  switchTransactionAmount: "Switch Transaction Amount",
  switchRemarksByEntryPerson: "Switch Remarks By Entry Person",
  panNumber: "Pan Number",
  registrantName: "RM Name",
  registrantEmail: "RM Email",
  investorFirstName: "Investor First Name",
  investorLastName: "Investor Last Name",
  investorName: "Investor Name",
  familyHead: "Family Head",
  systematicTraxType: "Systematic Transaction Type",
  systematicTraxFor: "Systematic Transaction For",
  systematicSchemeName: "Systematic Scheme Name",
  systematicMfAmcName: "Systematic MF AMC Name",
  systematicSourceScheme: "Systematic Source Scheme",
  systematicSchemeOption: "Systematic Scheme Option",
  systematicFolio: "Systematic Folio",
  sip_swp_stpAmount: "SIP/SWP/STP Amount",
  tenureOfSip_swp_stp: "Tenure of SIP/SWP/STP",
  sipPauseMonths: "SIP Pause Months",
  sip_stp_swpDate: "SIP/STP/SWP Date",
  firstTransactionAmount: "First Transaction Amount",
  systematicRemarksByEntryPerson: "Systematic Remarks By Entry Person",
  purch_RedempTraxType: "Purchase/Redemption Transaction Type",
  purch_redempMfAmcName: "Purchase/Redemption MF AMC Name",
  purch_redempSchemeName: "Purchase/Redemption Scheme Name",
  purch_redempSchemeOption: "Purchase/Redemption Scheme Option",
  purch_redempFolio: "Purchase/Redemption Folio",
  purch_redempTransactionUnits_Amount:
    "Purchase/Redemption Transaction Units/Amount",
  purch_redempTransactionAmount: "Purchase/Redemption Transaction Amount",
  purch_redempRemarksByEntryPerson:
    "Purchase/Redemption Remarks By Entry Person",
  switchMfAmcName: "Switch MF AMC Name",
  switchFromScheme: "Switch From Scheme",
  switchToScheme: "Switch To Scheme",
  switchSchemeOption: "Switch Scheme Option",
  switchFolio: "Switch Folio",
  switchTransactionUnits_Amount: "Switch Transaction Units/Amount",
  switchTransactionAmount: "Switch Transaction Amount",
  switchRemarksByEntryPerson: "Switch Remarks By Entry Person",
  transactionPreference: "Transaction Preference",
  systematicPaymentMode: "Systematic Payment Mode",
  systematicChequeNumber: "Systematic Cheque Number",
};

module.exports = transactionFields;